### change property in config source and call it in examinator service (foo.bar)

POST http://localhost:8080/actuator/bus-refresh

### and then, property should be changed in theology service


GET http://localhost:50128/test

###


POST http://localhost:8088/EXAMINATOR/exam
Content-Type: application/json

{
    "JAVA": "1",
    "THEOLOGY": "1"
}

###


GET http://localhost:8088/JAVA/random?amount=1

###


GET http://localhost:8088/THEOLOGY/random?amount=5

###
